### PR TITLE
PhantomJS bitbucket URL --> github URL

### PR DESCRIPTION
**Pull request by bradchesney79**
@pirog [#1359](https://github.com/kalabox/kalabox/issues/1359)

Here's the pull for the link to the most popular raw PhantomJS compressed file for npm instead of download limited bitbucket. Strange that the "Medium" publishing company is responsible for it. But, whatever.

Thank you so much for contributing code to Kalabox!

We will get to your PR as soon as we can but in the meantime you might want to
check to make sure you have done the following. **The more boxes you can check
the easier it will be for us to merge in your changes with confidence**
- [ Probably] My code passes relevant CI status checks
- [ N--Maybe it should] My code includes a test ([see here](https://github.com/kalabox/kalabox-app-php/blob/HEAD/CONTRIBUTING.md))
- [ Y ] My code includes an update to `CHANGELOG.md` ([see here](https://github.com/kalabox/kalabox-app-php/blob/HEAD/CHANGELOG.md))
- [ Yes in the README.md ] My code includes documentation updates if relevant.
- [ Yes ] I have pinged @pirog when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can
improve our process.

### CODE REVIEW

**Comment by bradchesney79** [comment]
What conflicts? I should have gone to the advanced git session-- (will likely watch it tonight online).

Probably the Changelog. If you prefer, I can resubmit a new pull request for easy merging.

**Comment by pirog** [comment]
@bradchesney79 i would just merge in the v0.12 branch, fix the conflicts and then push the changes up to this branch. 

if you don't want to wait i can review the changes and do the merge myself when we go through our PRs

**Comment by pirog** [comment]
hmmm not sure why all the tests are failing here.

**Comment by pirog** [comment]
@bradchesney79 finally merging this in as part of https://github.com/kalabox/kalabox-app-pantheon/pull/153

**Pull request closed without merging**
