### PR TITLE
KB Issue#776 Update to drush7, + update drush8 to next ver

### PR DESCRIPTION
**Pull request by labboy0276**
Sadness here: https://github.com/kalabox/kalabox/issues/776 get thsi over to drush7 and stop weidrness per Jun 23 comment from gerlingguy here: https://github.com/drush-ops/drush/issues/1409

= win.

### CODE REVIEW

**Comment by pirog** [comment]
this is a good start @labboy0276 but here are some small changes
1. drush7 install needs to go in the terminus image
2. you should also update the app skeletons kalabox.json to default to drush7

Optionally maybe we want to just remove support for drush 5/6 now? If you do remove them make sure to remove associated hacks in task.js

**Comment by reynoldsalec** [comment]
Hmm @labboy0276, this looks like the changes I made that worked on my machine...you're sure this doesn't work on another app?

**Comment by labboy0276** [comment]
@reynoldsalec did you use the codez I added above?  Adding it to the terminus container, etc?  I think my app just died and lost the DB so I gave up trying.

**Comment by pirog** [comment]
@labboy0276 @reynoldsalec maybe we want to just roll with drush8 for everything?

**Comment by labboy0276** [comment]
I am thinking the same thing @pirog. It seems that is where things are going in this world of the drupal.  I use drush8 outside my kb2 and it works just fine on all sites.  Only thing is on d7 and below sites we have to slap a --strict=0 on the end.

**Comment by pirog** [comment]
@labboy0276 ok. so maybe lets change this PR to only support drush 8 then?

**Comment by labboy0276** [comment]
ok i will try and do it this weekend, mu ha ha, bla ha ha

On Wed, Dec 9, 2015 at 3:10 PM, Mike Pirog notifications@github.com wrote:

> @labboy0276 https://github.com/labboy0276 ok. so maybe lets change this
> PR to only support drush 8 then?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalabox/kalabox-app-pantheon/pull/71#issuecomment-163377690
> .

## 

_John Ouellet_
_Sr Developer & Support Manager_
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
, Linkedin
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9,
and Facebook
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9

**Comment by pirog** [comment]
That would be great. We are going to roll alpha7 next Friday so it would be
great to get this in there.

On Wed, Dec 9, 2015 at 12:19 PM, John Ouellet notifications@github.com
wrote:

> ok i will try and do it this weekend, mu ha ha, bla ha ha
> 
> On Wed, Dec 9, 2015 at 3:10 PM, Mike Pirog notifications@github.com
> wrote:
> 
> > @labboy0276 https://github.com/labboy0276 ok. so maybe lets change
> > this
> > PR to only support drush 8 then?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/kalabox/kalabox-app-pantheon/pull/71#issuecomment-163377690
> > 
> > .
> 
> ## 
> 
> _John Ouellet_
> _Sr Developer & Support Manager_
> 415-470-3076
> www.kalamuna.com
> 
> Stay connected with Kalamuna on: Twitter
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> 
> > , Linkedin
> > <
> > http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> > ,
> > and Facebook
> > <
> > http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalabox/kalabox-app-pantheon/pull/71#issuecomment-163380779
> .

## 

Mike

## 

Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
, Linkedin
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9,
and Facebook
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9

**Comment by labboy0276** [comment]
@pirog I wouldn't merge this yet.  I removed everything but the drush 8 stuff.  I am getting this error now whenever I run drush commands:

```
Drush command terminated abnormally due to an unrecoverable error.       [error]
```

Not sure why, can you help out on this one Tom Brady style please

**Comment by pirog** [comment]
@labboy0276 running drush with verbose and debug mode on seems like a good first step

**Comment by pirog** [comment]
closing since we are just rolling wirht drush8 for now

**Pull request closed without merging**
