### PR TITLE
Allow host access to Redis container for redis-cli operations

### PR DESCRIPTION
**Pull request by dwoods**
Thank you so much for contributing code to Kalabox!

We will get to your PR as soon as we can but in the meantime you might want to
check to make sure you have done the following. **The more boxes you can check
the easier it will be for us to merge in your changes with confidence**
- [x] My code passes relevant CI status checks
- [ ] My code includes a test ([see here](http://pantheon.kalabox.io/developers/testing))
- [x] My code includes an update to `CHANGELOG.md` ([see here](https://github.com/kalabox/kalabox-app-php/blob/HEAD/CHANGELOG.md))
- [x] My code includes documentation updates if relevant.
- [x] I have pinged @pirog when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can
improve our process.

### CODE REVIEW

**Comment by dwoods** [comment]
@pirog Adding a host port to access Redis so you can examine and clear the cache.  

Not quite a solution to kalabox [issue #1183](https://github.com/kalabox/kalabox/issues/1183), but achieves the same result.  

I was going to add a 'kbox redis' command,  but I'm not sure which container to use for this...  Add redis-cli to the kalakbox/cli image and use that?

**Comment by pirog** [comment]
@dwoods this is good although i think figuring out #1183 would be ideal. If you've got motivation around looking at that i am more than happy to provide some high level advice on how best to do it! 

In the meantime, how are you accessing redis externally? You just downloading the redis-cli locally and then using that or is there some other tool you ar eusing?

LMK

**Comment by pirog** [comment]
@dwoods here is what the `kbox redis` command looks like in codez
https://github.com/kalabox/kalabox-app-pantheon/commit/d4d471d6fa925f249212c0996a6abeb67bd649ac

**Comment by dwoods** [comment]
@pirog Awesome!  was going to take a stab but time flies, thanks for putting this in :)

**Comment by pirog** [comment]
@dwoods sure thing and thanks for the PR. if you've got any inclination on helping on other pieces just ping me and im glad to provide and help and/or pointers!

**Pull request closed without merging**
