### PR TITLE
Updates to Pantheon Direct Comms

### PR DESCRIPTION
**Pull request by joshkoenig**
This should make comms with Pantheon's backend happier in the long haul.

### CODE REVIEW

**Comment by pirog** [comment]
@joshkoenig hmmm i wonder why all these tests are failing. let me rerun the build.

**Comment by pirog** [comment]
@joshkoenig weird. failed again. no idea why that would happen. Going to try the tests locally and see if those check out.

**Comment by joshkoenig** [comment]
Looks like it aborted because nothing came out for 10m. That's unexpected for this level of change I'd think.

**Comment by pirog** [comment]
Yeah i agree. I'm doing a few sanity checks right now. 

If your change somehow disrupted communicating with Pantheon this is how it would manifest in the tests i think. That said, it seems to work as expected when i create a site locally so NFI right now

**Comment by joshkoenig** [comment]
I did change the hostname. Maybe for some reason Travis can't connect to `terminus.pantheon.io`?

Shouldn't nodeJS die with a timeout at some point tho?

**Comment by pirog** [comment]
So it seems like it does throw an error when i give it a bogus host locally however the process seems to hang after the error instead of exiting with an exit code which is what the test framework is going to look for. Let me look into that a bit cause that definitely is not good. The tests all pass when i run them locally and i just reran the build for the commit before this and that checked out as well. 

Did you recently add this host eg is there a chance travis just hasn't gotten the DNS propagation yet?

**Comment by pirog** [comment]
@joshkoenig so looked into this some more and the hang on the error doesnt manifest when you run it non-interactively (like the tests do) so that shouldnt be our issue. 

Weirdly, when i pushed your branch directly to the kalabox project (ie under the kalabox namespace as opposed to yours) all the tests pass, so i guess there is just something weird when the tests run and you are outside the kalabox org.

**Pull request merged**
